apiVersion: v1
kind: Secret
metadata:
  name: tm-regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJkb2NrZXItcmVnaXN0cnkucW9kZXYuZXMiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImFtVnVhMmx1Y3pwS00yNXJNVzV6UUU0emVIVTEiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiSHR0cEhlYWRlcnMiOiB7CiAgICAgICAgICAgICAgICAiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjcgKGxpbnV4KSIKICAgICAgICB9Cn0K

---

apiVersion: v1
kind: Secret
metadata:
  name: tm-db-token
  namespace: {{ .Release.Namespace }}
data:
  username: dHJhZmZpYw==
  password: dHJhZmZpYw==

---

apiVersion: v1
kind: Secret
metadata:
  name: adminer-auth
  namespace: {{ .Release.Namespace }}
data:
  auth: dHJhZmZpY19tYW5hZ2VyOiRhcHIxJGFTN2NmTlU5JGNYenlOeFBza3hsN2pyaGJxTWE4Li4=