{{ if or (eq .Values.profile "pre") (eq .Values.profile "pro") }}
apiVersion: v1
kind: Service
metadata:
  name: tm-minio-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
    selector:
      app: minio
    ports:
      - port: {{ .Values.minio.apiPort }}
        name: api
        targetPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: tm-minio-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
    selector:
      app: minio
    type: NodePort
    ports:
      - port: {{ .Values.minio.consolePort }}
        name: web
        targetPort: 9001
        nodePort: 32091

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        
    spec:
      hostname: minio
      containers:
      - image: quay.io/minio/minio:{{ .Values.minio.imageTag }}
        imagePullPolicy: Always
        name: minio

        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: web
        command:
          - "/bin/sh"
          - "-ce"
          - "/usr/bin/docker-entrypoint.sh minio server --console-address :9001 /data"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
#            cpu: 80m
            memory: 512Mi

        env:
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            value: minio123

        volumeMounts:
          - mountPath: "/data"
            name: data

      volumes:
      - name: data
        hostPath:
          {{ if (eq .Values.profile "pre") }}
          path: /opt/volumes/traffic-manager/minio-dev/data
          {{ else if (eq .Values.profile "pro") }}
          path: /opt/volumes/traffic-manager/minio-test/data
          {{ end }}
          type: Directory
          

#        livenessProbe:
#          httpGet:
#            path: /minio/health/live
#            port: 9000
#          initialDelaySeconds: 60
#          periodSeconds: 60
{{ end }}
