apiVersion: v1
kind: Service
metadata:
  name: tm-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-db
spec:
    selector:
      app: tm-db
    ports:
      - port: 5432
        targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-db
  template:
    metadata:
      labels:
        app: tm-db
    spec:
      hostname: tm-db
      containers:
      - image: postgis/postgis:{{ .Values.tmdb.imageTag }}
        imagePullPolicy: Always
        name: tm-db
        ports:
        - containerPort: 5432

        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
#            cpu: 100m
            memory: 1024Mi

        env:
          - name: TZ
            value: "Europe/Madrid"
          - name: POSTGRES_DB
            value: {{ .Values.tmdb.dbName }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: tm-db-token
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tm-db-token
                key: password

        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: dbdata
          - mountPath: "/docker-entrypoint-initdb.d"
            name: dbinit
          - mountPath: "/shared"
            name: shared

      volumes:
      
      - name: dbdata
        hostPath:
          {{ if (eq .Values.profile "pre") }}
          path: /opt/volumes/traffic-manager/db-dev/data
          {{ else if (eq .Values.profile "pro") }}
          path: /opt/volumes/traffic-manager/db-pro/data
          {{ end }}
          type: Directory

      - name: dbinit
        hostPath:
          {{ if (eq .Values.profile "pre") }}
          path: /opt/volumes/traffic-manager/db-dev/entrypoint
          {{ else if (eq .Values.profile "pro") }}
          path: /opt/volumes/traffic-manager/db-pro/entrypoint
          {{ end }}
          type: Directory

      - name: shared
        hostPath:
          {{ if (eq .Values.profile "pre") }}
          path: /opt/volumes/traffic-manager/db-dev/shared
          {{ else if (eq .Values.profile "pro") }}
          path: /opt/volumes/traffic-manager/db-pro/shared
          {{ end }}
          type: Directory
