apiVersion: v1
kind: Service
metadata:
  name: tm-pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-pgadmin
spec:
    selector:
      app: tm-pgadmin
    ports:
      - port: {{ .Values.tmpgadmin.port }}
        targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-pgadmin
  template:
    metadata:
      labels:
        app: tm-pgadmin
    spec:
      hostname: tm-pgadmin
      containers:
      - image: dpage/pgadmin4:{{ .Values.tmpgadmin.imageTag }}
        imagePullPolicy: Always
        name: tm-pgadmin
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
#            cpu: 100m
            memory: 256Mi

        env:
          - name: TZ
            value: "Europe/Madrid"
          - name: PGADMIN_DEFAULT_EMAIL
            value: "tecnico@qualityobjects.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "traffic"

        volumeMounts:
          - mountPath: "/var/lib/pgadmin"
            name: pgadmin-data

      volumes:
      
      - name: pgadmin-data
        hostPath:
          {{ if (eq .Values.profile "pre") }}
          path: /opt/volumes/traffic-manager/pgadmin-dev/data
          {{ else if (eq .Values.profile "pro") }}
          path: /opt/volumes/traffic-manager/pgadmin-pro/data
          {{ end }}
          type: Directory